# Form implementation generated from reading ui file '.\ui\help.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(431, 393)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridFrame_3 = QtWidgets.QFrame(parent=Dialog)
        self.gridFrame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.gridFrame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_5.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.gridFrame_3)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gridFrame_3, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(0, 25, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 2)
        self.gridFrame = QtWidgets.QFrame(parent=Dialog)
        self.gridFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.gridFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_3.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gridFrame, 6, 0, 1, 2)
        self.closeButton = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setMinimumSize(QtCore.QSize(80, 25))
        self.closeButton.setObjectName("closeButton")
        self.gridLayout_2.addWidget(self.closeButton, 7, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 2)
        self.gridFrame_2 = QtWidgets.QFrame(parent=Dialog)
        self.gridFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.gridFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout_4.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=self.gridFrame_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gridFrame_2, 4, 0, 1, 2)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "This is used to search for Big Picture window.\n"
"Adjust depending on your Steam language."))
        self.label_2.setText(_translate("Dialog", "DESKTOP / GAMEMODE audio device"))
        self.label_4.setText(_translate("Dialog", "In millisecond.\n"
"Define how many time BigPictureTV should check for\n"
"big picture window presence.\n"
"Going under 100 ms is not recommended."))
        self.closeButton.setText(_translate("Dialog", "Close"))
        self.label_3.setText(_translate("Dialog", "Window check rate"))
        self.label_5.setText(_translate("Dialog", "The devices that will be used when switching modes.\n"
"You can specify keywords here.\n"
"If your device full name is \"Headset Earphone (CORSAIR VOID ELITE)\",\n"
"you can specify \"Corsair Headset\" and it will be valid."))
        self.label.setText(_translate("Dialog", "Steam Big Picture Keywords"))
