name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: python src/setup.py build

      - name: Upload project artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_win64
          path: build/${{ github.event.repository.name }}
